


function teste22() {
   console.log("afdasfdasf");
}

function Novoteste() {
  novaDiv = document.createElement("div");
    novaDiv.innerHTML = `<p> id: 1, "nacao": Hobbit, "casa": "O Condado", "descricao": "Os hobbits pés-peludos são o tipo mais comum de hobbit. São morenos, preferem planícies e regiões banhadas por rios. Os cascalvas tem a pele e o cabelo mais claros, são mais altos e mais esguios que os outros tipos de hobbit, preferem bosques e florestas para morar além de serem descendentes de elfos. Outros hobbits dizem que estes têm 'sangue de fada', por conta de sua ascendência. Os grados são tipos de hobbit mais robustos e frequentemente cultivam barbas. São mais próximos aos anões, e Sméagol costumava ser um cascalva antes de ser corrompido pelo anel", "personagens-saga": ["Bilbo Bolseiro", "Samwise Gamgee", "Frodo Bolseiro", "Peregrin Tûk", "Rosinha Villa"], "imagem": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Bilbo_Bols%C3%B3n.png/227px-Bilbo_Bols%C3%B3n.png"}</p>,
  <p>{"id": 2, "nacao": "Anão", "casa": "Brasil", "descricao": "Anões (no original Dwarf; no plural Dwarves) são uma raça de seres que habita Arda, a Terra pré-histórica fictícia que inclui o continente da Terra Média, nas obras fictícias de J. R. R. Tolkien. São geralmente ferreiros ou mineradores, inigualáveis até mesmo frente aos elfos em algumas de suas artes. Aparecem relativamente no livro O Hobbit (1937), esporadicamente em O Senhor dos Anéis (1954-1955), e nas publicações póstumas O Silmarillion (1977), Contos Inacabados (1980), e a série The History of Middle-earth (1983-1996), as três últimas editadas por seu filho e executor literário Christopher Tolkien.", "personagens-saga": ["Éomer", "Frodo", "Legolas"], "imagem": "URL-DA-IMAGEM"},</p>
  <p>{"id": 3, "nacao": "Cavaleiro de Rohan", "casa": "Portugal", "descricao": "Louis de Rohan Guémené, conhecido como Cavaleiro de Rohan era Grand Veneur de França já aos 20 anos e depois coronel dos guardas de Luís XIV, filho de Luís VIII de Rohan Guémené, 3º Duque de Montbazon e de Anne de Rohan. Participou da Guerra contra a Espanha e da Guerra da Holanda. Teve diversas aventuras amorosas", "personagens-saga": ["Zairo", "Atos", "Dartanhan"], "imagem": "URL-DA-IMAGEM"},</p>
  <p>{"id": 4, "nacao": "Guerreiro de Gondor", "casa": "Espanha", "descricao": "Aragorn II, filho de Arathorn é uma personagem fictícia criada pelo professor e filólogo britânico J. R. R. Tolkien na sua obra O Senhor dos Anéis, de que é um dos protagonistas. Aragorn era um Guardião do Norte, introduzido pela primeira vez com o nome Strider[nota 1] em Bree, como os hobbits continuaram a chamá-lo ao longo de O Senhor dos Anéis. Acabou sendo descoberto como herdeiro de Isildur e pretendente legítimo aos tronos de Arnor e Gondor. Também era um confidente de Gandalf e parte integrante da missão para destruir o Um Anel e derrotar o Senhor das Trevas Sauron.", "personagens-saga": ["Faramir", "Aragor", "Erodes"], "imagem": "URL-DA-IMAGEM"},</p>
  <p>{"id": 5, "nacao": "Elfo da Folresta", "casa": "Caatinga", "descricao": "Os Elfos, também conhecidos como Elfs ou Elves, são criaturas mitológicas cujas lendas têm como origem o Norte da Europa, com destaque para a região da Escandinávia e Alemanha Setentrional, com propagação inicial para as Ilhas Britânicas.", "personagens-saga": ["Glorfindel", "Gil-Galad ", "Fëanor"], "imagem": "URL-DA-IMAGEM"},</p>
  <p>{"id": 6, "nacao": "Elfo de Lothlórien", "casa": "Abismo de Helm", "descricao": "Durante a XIII século de Terceira Idade (TA), os governantes de Gondor formaram uma aliança estreita com os habitantes do território do norte de Rhovanion, um pai de três pessoas Casas do Edain da Primeira Era. Estes homens foram dizimados pela Grande Peste de 1636 TA, e ainda mais pelas invasões dos carrinhos de Pessoas-de- no final do XX século. Após essas invasões, alguns desses homens, liderados por um certo Frumgar, migraram para o vale superior do Anduin em 1977 TA. No local, eles entraram em conflito com os Anões sobre o compartilhamento do tesouro do dragão Scatha, morto por Fram, filho de Frumgar. Esses homens, que tomaram o nome de Éothéod, viveram por vários séculos ao redor das nascentes do Anduin, mas se tornaram cada vez mais numerosos e se sentiam confinados em suas terras. Apesar do afastamento, eles mantiveram laços com Gondor, e quando o Administrador Cirion se viu atacado por hordas de Orientais e Orcs, em 2510 AT, ele chamou Eorl, o Jovem, o novo Senhor dos Éothéod. Ele chegou inesperadamente e venceu a batalha decisiva dos Campos de Celebrant.", "personagens-saga": ["Théoden", "Théodred", "Deorwine"], "imagem": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Cavalierrohan.jpg/220px-Cavalier-rohan.jpg"},</p>
  <p>{"id": 7, "nacao": "Orc Snaga", "casa": "Caverna", "descricao": "Nas obras fictícias de J. R. R. Tolkien, Lothlórien é um reino e floresta dos elfos restantes na Terra Média durante a Terceira Era.[1] O reino tem um papel importante em O Senhor dos Anéis[2] como o centro élfico de resistência contra Sauron e é um símbolo à estética élfica de preservação florestal que fornece um espaço 'fora do tempo' para os personagens que ambos vivem e visitam lá.[3] Com Lothlórien, Tolkien de outra forma reconcilia ideias conflitantes sobre o tempo distorcido dos Contos de Fadas de várias fontes tradicionais, como Tomás, o Rimador (séculos XIII e XIV) e o conto folclórico dinamarquês Elverhøj (1828).[4]", "personagens-saga": ["Dark Lord", "Sauron", "Valar Melko"], "imagem": "URL-DA-IMAGEM"},</p>
  <p>{"id": 8, "nacao": "França", "casa": "Colina", "descricao": "Os Uruk-hai eram mais usados como soldados por ser mais fortes e mais altos do que a maioria dos outros orcs, os Uruk eram bruscos e não sentiam medo de quase nada por ser tao altos quanto os homens eles se superavam em tudo menos inteligência, e por essas qualidades evidentes os Uruk consideravam-se mais fortes do que alguns dos outros orcs por isso criaturas menores como alguns goblins não se atreveriam a  se meter com eles. Os Uruks  não se enfraqueciam a luz do sol isso os ajudavam muito pôs em guerras de longa distancia eles não perdiam tempo correndo só a noite.      Lurtz observando a sua forca em Insengard após o cargo de lama:", "personagens-saga": ["Uruk-hai", "Gollum", "Gandalf"], "imagem": "URL-DA-IMAGEM"</p>

`;
  document.body.append(novaDiv);
}